### ISSUE TITLE
PHP Warning: A non-numeric value encountered in ...

### ISSUE THREAD

**Issue by rowild** [AstCommodore/threeme#16]
On TYPO3 8.7.10 with php 7.1.11, threeme throws an error message:

PHP Warning: A non-numeric value encountered in ... vendor/typo3fluid/fluid/src/Core/Parser/SyntaxTree/Expression/MathExpressionNode.php line 79

Clean install and only extension.

**Comment by AstCommodore** [comment]
Yes, it's because of the use of FLUID variables in a MASK template. I just see it a few days ago, e.g.:

`<f:variable name="mediaDesktop2x" value="{mediaDesktop * 2}" />`

## Workarround:
I used a example form https://usetypo3.com/24-fluid-tips.html#c430 - I will figure out it in detail. Meanwhile you could just delete the FLUID vars, they aren't used by default yet.

Take a lock into Fluid > MASK > Content > Partials > PictureSet and search for these vars the whole extension.

**Comment by rowild** [comment]
Thanks for the hint!

**Comment by AstCommodore** [comment]
Seems to be a problem targeting FLUID itself, see https://github.com/TYPO3/Fluid/issues/300

**Comment by AstCommodore** [comment]
I removed the (unused) variables, see error is gone.

**Comment by ValentinHuwer** [comment]
I do not do any calculations in my template, yet I get the same error. When I use the template outside Mask, it works fine. @AstCommodore I did not really get your workaround, it would be very very helpful if you could clarify

**Comment by AstCommodore** [comment]
@ValentinHuwer You mean, when using the partial 'PictureSet' outside of a MASK element/template, the error isn't thrown? 

This issue is more than two years old, the targeted Threeme version isn't supported anymore and we are working on a version for T3 v10 at time. But time is rar ...

**Comment by ValentinHuwer** [comment]
@AstCommodore All good, I solved it the Typo3 way by spending a few hours changing everything forth and back ... works now. Thank you for responding though.
